<a href="https://colab.research.google.com/github/mariuszDolinski/Data-Science-Course/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [ ]:
x=np.array([1, 3])
print(x)
type(x)

[1 3]


(2,)

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.2, 3.4, 2.7])
print(x)

[1.2 3.4 2.7]


In [ ]:
x.dtype

dtype('float64')

2D Array

In [ ]:
x= np.array([[1, 2], [-3, 1]])
print(x)

[[ 1  2]
 [-3  1]]


In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x.size

4

In [ ]:
x=np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.size

6

In [ ]:
x.shape

(2, 3)

3D Array

In [ ]:
x = np.array(
    [
        [
            [4, 3, 1],
            [3, 1, 2]
        ],
        [
            [4, 1, 3],
            [4, 2, 1]
        ]
    ]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 3)

In [ ]:
x.size

12

Tablice wbudowane

In [ ]:
np.zeros(shape=(4, 10), dtype='int') #tablica z samymi zerami

In [ ]:
np.ones(shape=(5, 5)) #tablica z samymi jedynkami

In [ ]:
np.full(shape=(3, 3), fill_value=4, dtype='int') #tablica z dowolną wartością

In [ ]:
np.arange(10) #tablica z zakresu

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=11) #liniowo rozłożone (w równych odstępach)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape(5, -1) # -1 powoduje dobranie odpowiedniej liczby kolumn (może być też pierwszym parametrem)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Operacje na tablicach

In [2]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])

In [3]:
A + B #np.Add(A, B)

array([6, 0, 7, 4])

In [4]:
A - B #np.Substract(A, B)

array([0, 2, 1, 0])

In [5]:
A * B #np.multiply(A, B)

array([ 9, -1, 12,  4])

In [6]:
A/B #np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [7]:
A + 3

array([6, 4, 7, 5])

In [8]:
2 * A

array([6, 2, 8, 4])

In [9]:
A - 3*B

array([-6,  4, -5, -4])

In [10]:
C = np.array([[1, 2], [3, 4]])
D = np.array([[6, 0], [1, -2]])
print(C)
print(D)

[[1 2]
 [3 4]]
[[ 6  0]
 [ 1 -2]]


In [11]:
C * D #mnożenie tablicowe

array([[ 6,  0],
       [ 3, -8]])

In [12]:
np.dot(C, D) #mnożenie macierzowe

array([[ 8, -4],
       [22, -8]])

In [13]:
C.dot(D)

array([[ 8, -4],
       [22, -8]])

In [14]:
C @ D

array([[ 8, -4],
       [22, -8]])

Liczby pseudolosowe

In [15]:
np.random.seed() #ziarno losowe, za każdym powtórzeniem będzie ten sam wynik

In [17]:
np.random.randn() #rozkład normalny N(0,1)

-0.5251067419669305

In [19]:
np.random.randn(10, 4)

array([[-0.02285847,  0.21665923, -1.38159742,  0.62330836],
       [ 0.32979595, -0.11796031,  1.14773795,  0.35667725],
       [ 1.35848192, -0.63990161, -0.03896861, -0.67968089],
       [ 1.11807597, -0.06877249, -0.73856706, -0.10908153],
       [-1.13390559,  0.25217209, -0.05672352,  0.67607747],
       [-0.87920356, -1.65558635, -1.50045275, -0.29879152],
       [ 0.45173638,  1.49425598,  2.89318269, -2.96067584],
       [-0.6920939 , -0.2793649 , -0.99972577,  1.46591136],
       [-1.4669591 ,  1.15149605, -0.32015872, -0.80527705],
       [-0.65628525, -0.94031105,  0.07956647, -1.38832549]])

In [20]:
np.random.rand() #rozkład jdnostajny na [0,1]

0.8653520477958982

In [21]:
np.random.rand(5)

array([0.6313352 , 0.07189912, 0.1802701 , 0.91068188, 0.90688417])

In [23]:
np.random.randint(10) #losowy int z zakresu [0,10)

5

In [26]:
np.random.randint(low=10, high=100, size=10) #min. max-1, ilość

array([83, 71, 43, 93, 91, 26, 92, 46, 60, 59])

In [29]:
np.random.choice(["python", "java", "sql", "c#"]) #losowy element z listy

'python'

In [37]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.random.shuffle(data) #zmienia kolejność elementów, od razu przypisuje wynik do tej samej zmiennej
data

array([7, 8, 0, 3, 2, 5, 6, 1, 4, 9])