<a href="https://colab.research.google.com/github/mariuszDolinski/Data-Science-Course/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [ ]:
x=np.array([1, 3])
print(x)
type(x)

[1 3]


(2,)

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.2, 3.4, 2.7])
print(x)

[1.2 3.4 2.7]


In [ ]:
x.dtype

dtype('float64')

In [5]:
x = np.array([1, 2, 3], dtype='float')
x.dtype

dtype('float64')

In [7]:
x = np.array([1, 2, 3], dtype='complex')
print(x)

[1.+0.j 2.+0.j 3.+0.j]


In [8]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [10]:
x = np.array([1, 2, 3], dtype='uint8') #unsigned int 0-255 przydatne do przechywania danych obrazów (kolor pojedynczego piksela)
x.dtype

dtype('uint8')

2D Array

In [ ]:
x= np.array([[1, 2], [-3, 1]])
print(x)

[[ 1  2]
 [-3  1]]


In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x.size

4

In [ ]:
x=np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.size

6

In [ ]:
x.shape

(2, 3)

3D Array

In [ ]:
x = np.array(
    [
        [
            [4, 3, 1],
            [3, 1, 2]
        ],
        [
            [4, 1, 3],
            [4, 2, 1]
        ]
    ]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 3)