<a href="https://colab.research.google.com/github/mariuszDolinski/Data-Science-Course/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [ ]:
x=np.array([1, 3])
print(x)
type(x)

[1 3]


(2,)

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.2, 3.4, 2.7])
print(x)

[1.2 3.4 2.7]


In [ ]:
x.dtype

dtype('float64')

2D Array

In [ ]:
x= np.array([[1, 2], [-3, 1]])
print(x)

[[ 1  2]
 [-3  1]]


In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x.size

4

In [ ]:
x=np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.size

6

In [ ]:
x.shape

(2, 3)

3D Array

In [ ]:
x = np.array(
    [
        [
            [4, 3, 1],
            [3, 1, 2]
        ],
        [
            [4, 1, 3],
            [4, 2, 1]
        ]
    ]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 3)

In [ ]:
x.size

12

Tablice wbudowane

In [ ]:
np.zeros(shape=(4, 10), dtype='int') #tablica z samymi zerami

In [ ]:
np.ones(shape=(5, 5)) #tablica z samymi jedynkami

In [ ]:
np.full(shape=(3, 3), fill_value=4, dtype='int') #tablica z dowolną wartością

In [ ]:
np.arange(10) #tablica z zakresu

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=11) #liniowo rozłożone (w równych odstępach)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape(5, -1) # -1 powoduje dobranie odpowiedniej liczby kolumn (może być też pierwszym parametrem)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Operacje na tablicach

In [ ]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])

In [ ]:
A + B #np.Add(A, B)

array([6, 0, 7, 4])

In [ ]:
A - B #np.Substract(A, B)

array([0, 2, 1, 0])

In [ ]:
A * B #np.multiply(A, B)

array([ 9, -1, 12,  4])

In [ ]:
A/B #np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A + 3

array([6, 4, 7, 5])

In [ ]:
2 * A

array([6, 2, 8, 4])

In [ ]:
A - 3*B

array([-6,  4, -5, -4])

In [ ]:
C = np.array([[1, 2], [3, 4]])
D = np.array([[6, 0], [1, -2]])
print(C)
print(D)

[[1 2]
 [3 4]]
[[ 6  0]
 [ 1 -2]]


In [ ]:
C * D #mnożenie tablicowe

array([[ 6,  0],
       [ 3, -8]])

In [ ]:
np.dot(C, D) #mnożenie macierzowe

array([[ 8, -4],
       [22, -8]])

In [ ]:
C.dot(D)

array([[ 8, -4],
       [22, -8]])

In [ ]:
C @ D

array([[ 8, -4],
       [22, -8]])

Liczby pseudolosowe

In [ ]:
np.random.seed() #ziarno losowe, za każdym powtórzeniem będzie ten sam wynik

In [ ]:
np.random.randn() #rozkład normalny N(0,1)

-0.5251067419669305

In [ ]:
np.random.randn(10, 4)

array([[-0.02285847,  0.21665923, -1.38159742,  0.62330836],
       [ 0.32979595, -0.11796031,  1.14773795,  0.35667725],
       [ 1.35848192, -0.63990161, -0.03896861, -0.67968089],
       [ 1.11807597, -0.06877249, -0.73856706, -0.10908153],
       [-1.13390559,  0.25217209, -0.05672352,  0.67607747],
       [-0.87920356, -1.65558635, -1.50045275, -0.29879152],
       [ 0.45173638,  1.49425598,  2.89318269, -2.96067584],
       [-0.6920939 , -0.2793649 , -0.99972577,  1.46591136],
       [-1.4669591 ,  1.15149605, -0.32015872, -0.80527705],
       [-0.65628525, -0.94031105,  0.07956647, -1.38832549]])

In [ ]:
np.random.rand() #rozkład jdnostajny na [0,1]

0.8653520477958982

In [ ]:
np.random.rand(5)

array([0.6313352 , 0.07189912, 0.1802701 , 0.91068188, 0.90688417])

In [ ]:
np.random.randint(10) #losowy int z zakresu [0,10)

5

In [ ]:
np.random.randint(low=10, high=100, size=10) #min. max-1, ilość

array([83, 71, 43, 93, 91, 26, 92, 46, 60, 59])

In [ ]:
np.random.choice(["python", "java", "sql", "c#"]) #losowy element z listy

'python'

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data) #zmienia kolejność elementów, od razu przypisuje wynik do tej samej zmiennej
data

array([7, 8, 0, 3, 2, 5, 6, 1, 4, 9])

Funkcje wbudowne

In [2]:
np.exp(1) #e^1

2.718281828459045

In [4]:
np.sqrt(25) #pierwiastek kwadratowy

5.0

In [5]:
np.all([2, 3, 1]) #czy wszystkie wartości są prawdziwe

True

In [6]:
np.any([0, 0, 0]) #czy jakikolwiek element jest prawdziwy

False

In [7]:
A = np.random.rand(5)
A

array([0.21419416, 0.69233699, 0.9501659 , 0.05324411, 0.83653687])

In [8]:
np.argmax(A) #indeks największej wartości

2

In [9]:
np.argmin(A) #indeks najmniejszej wartości

3

In [10]:
np.argsort(A) #indeksy posortowanych rosnąco wartości

array([3, 0, 1, 4, 2])

In [11]:
np.max(A)
np.min(A)

0.05324410929681589

In [12]:
np.mean(A) #średnia

0.5492956067383148

In [13]:
np.median(A) #mediana

0.6923369933563518

In [14]:
np.std(A) #odchylenie standardowe

0.35271105597217256

Indeksowanie

In [16]:
A=np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [18]:
A[:2]

array([0, 1])

In [19]:
A[2:7]

array([2, 3, 4, 5, 6])

In [21]:
A[[0,2]]

array([0, 2])

In [22]:
A[-1]

19

In [27]:
B = A.reshape(4,5)
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
B[0]

array([0, 1, 2, 3, 4])

In [29]:
B[:,1]

array([ 1,  6, 11, 16])

In [30]:
B[:,-1]

array([ 4,  9, 14, 19])

In [32]:
B[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [35]:
B[1,2] = 15
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 15,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Itercja

In [37]:
for row in B:
    print(row[:3])

[0 1 2]
[ 5  6 15]
[10 11 12]
[15 16 17]


In [40]:
for item in A.flat: #flat spłaszcz tablicę do jednego wymiaru
    print(item)

0
1
2
3
4
5
6
15
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmiary tablicy

In [41]:
B.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 15,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
B.T #transponowanie

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 15, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [46]:
C = np.arange(-10, 10, 0.5)
C = C.reshape(10, -1)
C

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [48]:
C > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [49]:
C[C > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [51]:
np.bitwise_and(C > -5, C < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [52]:
C[np.bitwise_and(C > -5, C < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])