<a href="https://colab.research.google.com/github/mariuszDolinski/Data-Science-Course/blob/main/NumPy_Statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.26.4'

In [3]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])

In [4]:
price.sum() #suma wszystkich elementów tablicy

4650.1

In [5]:
price.sum(axis=0) #suma poszczególnych kolumn

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [6]:
price.sum(axis=1) #suma poszczególnych wierszy

array([1049.7, 2049.4, 1551. ])

In [7]:
np.min(price, axis=0) #minimum poszczególnych kolumn

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

In [8]:
np.max(price, axis=1) #maximum poszczególnych wierszy

array([1000., 2000., 1500.])

In [9]:
np.median(price) #mediana całej tablicy

12.6

In [10]:
np.mean(price, axis=0) #średnia poszczególnych kolumn

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

In [11]:
np.std(price, axis=0) #odchylenie standardowe poszczególnych kolumn

array([1.24721913e-01, 2.49443826e-01, 2.05480467e-01, 4.10960934e-01,
       4.08248290e+02])

In [12]:
np.var(price, axis=0) #wariancja poszczególnych kolumn

array([1.55555556e-02, 6.22222222e-02, 4.22222222e-02, 1.68888889e-01,
       1.66666667e+05])