<a href="https://colab.research.google.com/github/mariuszDolinski/Data-Science-Course/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [ ]:
x=np.array([1, 3])
print(x)
type(x)

[1 3]


(2,)

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.2, 3.4, 2.7])
print(x)

[1.2 3.4 2.7]


In [ ]:
x.dtype

dtype('float64')

2D Array

In [ ]:
x= np.array([[1, 2], [-3, 1]])
print(x)

[[ 1  2]
 [-3  1]]


In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x.size

4

In [ ]:
x=np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.size

6

In [ ]:
x.shape

(2, 3)

3D Array

In [ ]:
x = np.array(
    [
        [
            [4, 3, 1],
            [3, 1, 2]
        ],
        [
            [4, 1, 3],
            [4, 2, 1]
        ]
    ]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 3)

In [ ]:
x.size

12

Tablice wbudowane

In [ ]:
np.zeros(shape=(4, 10), dtype='int') #tablica z samymi zerami

In [ ]:
np.ones(shape=(5, 5)) #tablica z samymi jedynkami

In [ ]:
np.full(shape=(3, 3), fill_value=4, dtype='int') #tablica z dowolną wartością

In [11]:
np.arange(10) #tablica z zakresu

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [17]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [18]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [21]:
np.linspace(start=0, stop=1, num=11) #liniowo rozłożone (w równych odstępach)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [23]:
A = np.arange(15)
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
A.reshape(5, -1) # -1 powoduje dobranie odpowiedniej liczby kolumn (może być też pierwszym parametrem)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])