<a href="https://colab.research.google.com/github/mariuszDolinski/Data-Science-Course/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [11]:
x=np.array([1, 3])
print(x)
type(x)

[1 3]


(2,)

In [10]:
x.ndim

1

In [12]:
x.shape

(2,)

In [13]:
x.size

2

In [14]:
x.dtype

dtype('int64')

In [15]:
x = np.array([1.2, 3.4, 2.7])
print(x)

[1.2 3.4 2.7]


In [17]:
x.dtype

dtype('float64')

2D Array

In [19]:
x= np.array([[1, 2], [-3, 1]])
print(x)

[[ 1  2]
 [-3  1]]


In [22]:
x.ndim

2

In [23]:
x.shape

(2, 2)

In [24]:
x.size

4

In [26]:
x=np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [27]:
x.size

6

In [28]:
x.shape

(2, 3)

3D Array

In [30]:
x = np.array(
    [
        [
            [4, 3, 1],
            [3, 1, 2]
        ],
        [
            [4, 1, 3],
            [4, 2, 1]
        ]
    ]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [31]:
x.ndim

3

In [32]:
x.shape

(2, 2, 3)