<a href="https://colab.research.google.com/github/mariuszDolinski/Data-Science-Course/blob/main/NumPy_LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [ ]:
np.linalg.norm(v1) #norma wektora

4.123105625617661

In [ ]:
v2 = np.array([4, 2, 3, 1])
v2

array([4, 2, 3, 1])

In [ ]:
np.linalg.norm(v2) #norma wektora

5.477225575051661

In [ ]:
p = np.array([3, 0])
q = np.array([0, 4])

In [ ]:
np.linalg.norm(p - q) #odległość dwóch punktów

5.0

In [ ]:
A = np.array([[1,2,3],[-1,0,1],[0,0,4]])
B = np.array([[1,0],[-1,3],[2,1]])

In [ ]:
np.dot(A, B)

array([[5, 9],
       [1, 1],
       [8, 4]])

In [ ]:
round(np.linalg.det(A))

8

In [ ]:
np.trace(A)

5

In [ ]:
np.eye(4, dtype='int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
AI = np.linalg.inv(A)
AI

array([[ 0.  , -1.  ,  0.25],
       [ 0.5 ,  0.5 , -0.5 ],
       [ 0.  ,  0.  ,  0.25]])

In [ ]:
np.set_printoptions(precision=4, suppress=True)
np.dot(A, AI)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])